### ISSUE TITLE
Shoulda matcher needed to pass set_flash? 

### ISSUE THREAD

**Issue by crosskayla** [learn-co-curriculum/routing-nested-resources-lab#9]
I was getting the following error for the spec file (not the controller it was testing):

`SongsController GET show with  artist redirects to artists songs when artist song not found
     Failure/Error: expect(controller).to set_flash[:alert]
     
     NameError:
       undefined local variable or method `set_flash' for #<RSpec::ExampleGroups::SongsController::GETShowWithArtist:0x007f85bb8d88b0>
     # ./spec/controllers/songs_controller_spec.rb:35:in `block (3 levels) in <top (required)>'`

The gem 'shoulda' is included in this lab but not configured, so I just added the following to spec/rails_helper.rb and the test worked:

```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

([source](https://github.com/thoughtbot/shoulda-matchers/issues/903))

**Comment by kjdub01** [comment]
I had the same problem and used the same fix

**Comment by drakeltheryuujin** [comment]
Looks like this may have been fixed in this [commit](https://github.com/learn-co-curriculum/routing-nested-resources-lab/commit/a19d8e08149bdd9cb5ed703c8a7120c8a594c40c). 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
